name: PyPI

on:
  release:
    types:
      - created

jobs:
  publish:
    name: PyPI
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.PYPI_USERNAME }}
      PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install poetry
      - name: Publish package
        run: |
          poetry build
          poetry publish --username $USERNAME --password $PASSWORD
